import Head from "next/head";
import Image from "next/image";
import SemiFy from "../imgs/SemiFy.png";
import { useState, useEffect } from "react";
import { Login, Signup } from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [loginPage, setLoginPage] = useState(false);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.headline}>
          <h1 className={styles.title}>
            Welcome to <a href="">SemiFy!</a>
          </h1>
          <Image src={SemiFy} alt="SemiFy" width={200} height={200} />
        </div>
        {loginPage ? <Login setLoginPage={setLoginPage} /> : <Signup setLoginPage={setLoginPage} />}
       {/*  */}
        <div className={styles.footer}>
          <a target="_blank">Copyright ©2022-2023<br/>
          All rights reserved. Made by Snowy </a>
        </div>
      </main>

    </div>
  );
}
